SERVICE_CATEGORIES = {
    "AI": {
        "ChatGPT": ["openai.com", "chat.openai.com", "chatgpt.com", "www.chatgpt.com", "cdn.openai.com", "ab.chatgpt.com", "auth0.openai.com"],
        "Claude": ["claude.ai", "www.claude.ai", "anthropic.com", "www.anthropic.com"],
        "Copilot": ["copilot.microsoft.com", "githubcopilot.com", "copilot.github.com"],
        "DeepSeek": ["deepseek.com", "www.deepseek.com", "chat.deepseek.com"],
        "Gemini": ["gemini.google.com"],
        "Grok": ["grok.com", "x.ai", "www.x.ai"],
        "Manus": ["manus.im", "www.manus.im"],
        "Meta AI": ["meta.ai", "www.meta.ai"],
        "Perplexity": ["perplexity.ai", "www.perplexity.ai"],
    },
    "CDN": {
        "Cloudflare": ["cloudflare-dns.com", "one.one.one.one", "warp.cloudflare.com", "api.cloudflareclient.com"],
    },
    "Dating": {
        "Plenty of Fish": ["pof.com", "www.pof.com"],
        "Tinder": ["tinder.com", "www.tinder.com", "gotinder.com"],
        "Wizz": ["wizzapp.net", "www.wizzapp.net"],
    },
    "Gambling": {
        "Betano": ["betano.com", "www.betano.com"],
        "Betfair": ["betfair.com", "www.betfair.com"],
        "Betway": ["betway.com", "www.betway.com"],
        "Blaze": ["blaze.com", "www.blaze.com", "blaze1.com"],
    },
    "Games": {
        "Activision Blizzard": ["activision.com", "www.activision.com"],
        "Battle.net": ["battle.net", "www.battle.net", "battlenet.com.cn"],
        "Blizzard Entertainment": ["blizzard.com", "www.blizzard.com", "blzstatic.com"],
        "Electronic Arts": ["ea.com", "www.ea.com", "easports.com"],
        "Epic Games": ["epicgames.com", "www.epicgames.com", "unrealengine.com", "easistent.com"],
        "GOG": ["gog.com", "www.gog.com", "gog-statics.com"],
        "IO Interactive": ["ioi.dk", "www.ioi.dk", "hitman.com"],
        "League of Legends": ["leagueoflegends.com", "www.leagueoflegends.com"],
        "Minecraft": ["minecraft.net", "www.minecraft.net", "mojang.com"],
        "Nintendo": ["nintendo.com", "www.nintendo.com", "nintendo.net"],
        "Origin": ["origin.com", "www.origin.com"],
        "Playstation": ["playstation.com", "www.playstation.com", "playstation.net", "sonyentertainmentnetwork.com"],
        "Riot Games": ["riotgames.com", "www.riotgames.com", "riot.com"],
        "Roblox": ["roblox.com", "www.roblox.com", "rbxcdn.com"],
        "Rockstar Games": ["rockstargames.com", "www.rockstargames.com", "ros.rockstargames.com"],
        "Steam": ["steampowered.com", "steamcommunity.com", "steamcdn.com", "steamstore.com", "steamstatic.com"],
        "Ubisoft": ["ubisoft.com", "www.ubisoft.com", "ubi.com", "uplay.com"],
        "Valorant": ["playvalorant.com", "www.playvalorant.com"],
        "Wargaming": ["wargaming.net", "www.wargaming.net"],
        "Warner Bros. Games": ["wbgames.com", "www.wbgames.com"],
        "Xbox Live": ["xbox.com", "www.xbox.com", "xboxlive.com"],
    },
    "File Hosting": {
        "Box": ["box.com", "www.box.com", "app.box.com"],
        "Dropbox": ["dropbox.com", "www.dropbox.com", "dropboxapi.com", "dropboxstatic.com"],
        "Flickr": ["flickr.com", "www.flickr.com", "staticflickr.com"],
        "Imgur": ["imgur.com", "www.imgur.com", "imgurcdn.com"],
    },
    "Messaging": {
        "KakaoTalk": ["kakao.com", "www.kakao.com", "kakaocorp.com"],
        "Kik": ["kik.com", "www.kik.com"],
        "MAX": ["max.ru", "www.max.ru"],
        "Microsoft Teams": ["teams.microsoft.com", "teams.live.com"],
        "Olvid": ["olvid.io", "www.olvid.io"],
        "Signal": ["signal.org", "www.signal.org", "whispersystems.org"],
        "Skype": ["skype.com", "www.skype.com", "login.skype.com"],
        "Slack": ["slack.com", "www.slack.com", "slack-edge.com"],
        "Telegram": ["telegram.org", "t.me", "cdn-telegram.org"],
        "Viber": ["viber.com", "www.viber.com"],
        "WeChat": ["wechat.com", "www.wechat.com", "weixin.qq.com"],
        "WhatsApp": ["whatsapp.com", "www.whatsapp.com", "whatsapp.net", "cdn.whatsapp.net"],
    },
    "Privacy Tools": {
        "iCloud Private Relay": ["mask.icloud.com", "mask-h2.icloud.com"],
        "Privacy": ["privacy.com", "www.privacy.com"],
        "Proton": ["proton.me", "www.proton.me", "protonmail.com", "protonvpn.com"],
    },
    "Shopping": {
        "AliExpress": ["aliexpress.com", "www.aliexpress.com"],
        "Amazon": ["amazon.com", "www.amazon.com", "amazon.de", "amazon.co.uk"],
        "CoolApk": ["coolapk.com", "www.coolapk.com"],
        "eBay": ["ebay.com", "www.ebay.com"],
        "Lazada": ["lazada.com", "www.lazada.com"],
        "Mercado Libre": ["mercadolibre.com", "www.mercadolibre.com", "mercadolivre.com"],
        "Shein": ["shein.com", "www.shein.com"],
        "Shopee": ["shopee.com", "www.shopee.com"],
        "Temu": ["temu.com", "www.temu.com"],
        "Xiaohongshu": ["xiaohongshu.com", "www.xiaohongshu.com", "xhscdn.com"],
    },
    "Social Media": {
        "4chan": ["4chan.org", "www.4chan.org", "4cdn.org"],
        "500px": ["500px.com", "www.500px.com"],
        "9GAG": ["9gag.com", "www.9gag.com"],
        "Amino": ["aminoapps.com", "www.aminoapps.com"],
        "Bluesky": ["bsky.app", "www.bsky.app", "bsky.social"],
        "Clubhouse": ["clubhouse.com", "www.clubhouse.com", "joinclubhouse.com"],
        "Discord": ["discord.com", "www.discord.com", "discordapp.com", "cdn.discordapp.com", "discord.gg"],
        "Douban": ["douban.com", "www.douban.com"],
        "Facebook": ["facebook.com", "www.facebook.com", "m.facebook.com", "fbcdn.net", "fb.com", "fbsbx.com"],
        "Instagram": ["instagram.com", "www.instagram.com", "cdninstagram.com", "instagram.fotp1-1.fna.fbcdn.net"],
        "KOOK": ["kookapp.cn", "www.kookapp.cn"],
        "LINE": ["line.me", "www.line.me", "line-apps.com"],
        "LinkedIn": ["linkedin.com", "www.linkedin.com", "licdn.com"],
        "Mail.ru": ["mail.ru", "www.mail.ru"],
        "Mastodon": ["joinmastodon.org", "www.joinmastodon.org"],
        "Odysee": ["odysee.com", "www.odysee.com"],
        "OK.ru": ["ok.ru", "www.ok.ru"],
        "OnlyFans": ["onlyfans.com", "www.onlyfans.com"],
        "Pinterest": ["pinterest.com", "www.pinterest.com", "pinimg.com"],
        "Reddit": ["reddit.com", "www.reddit.com", "redditmedia.com", "redditstatic.com", "redd.it"],
        "Snapchat": ["snapchat.com", "www.snapchat.com", "sc-cdn.net"],
        "TikTok": ["tiktok.com", "www.tiktok.com", "m.tiktok.com", "tiktokcdn.com", "tiktokv.com", "musical.ly"],
        "Tumblr": ["tumblr.com", "www.tumblr.com"],
        "VK": ["vk.com", "www.vk.com", "vk.me"],
        "X/Twitter": ["twitter.com", "www.twitter.com", "x.com", "www.x.com", "twimg.com", "t.co"],
        "Zhihu": ["zhihu.com", "www.zhihu.com"],
    },
    "Software Development": {
        "Nvidia": ["nvidia.com", "www.nvidia.com", "nvidiagrid.net"],
        "Google Play Store": ["play.google.com", "android.clients.google.com"],
    },
    "Streaming": {
        "Amazon Prime Video": ["primevideo.com", "www.primevideo.com"],
        "Apple TV+": ["tv.apple.com"],
        "Bigo Live": ["bigo.tv", "www.bigo.tv"],
        "Bilibili": ["bilibili.com", "www.bilibili.com"],
        "Canais Globo": ["globo.com", "www.globo.com"],
        "Claro": ["claro.com", "www.claro.com"],
        "Crunchyroll": ["crunchyroll.com", "www.crunchyroll.com"],
        "Dailymotion": ["dailymotion.com", "www.dailymotion.com"],
        "Deezer": ["deezer.com", "www.deezer.com"],
        "DirecTV Go": ["directvgo.com", "www.directvgo.com"],
        "Discovery+": ["discoveryplus.com", "www.discoveryplus.com"],
        "Disney+": ["disneyplus.com", "www.disneyplus.com"],
        "ESPN": ["espn.com", "www.espn.com"],
        "FIFA+": ["fifa.com", "www.fifa.com"],
        "Globoplay": ["globoplay.globo.com", "globoplay.com"],
        "HBO Max": ["max.com", "www.max.com", "hbomax.com"],
        "Hulu": ["hulu.com", "www.hulu.com"],
        "iHeartRadio": ["iheart.com", "www.iheart.com"],
        "iQIYI": ["iq.com", "www.iq.com", "iqiyi.com"],
        "Lionsgate+": ["lionsgateplus.com", "www.lionsgateplus.com"],
        "Looke": ["looke.com.br", "www.looke.com.br"],
        "Nebula": ["nebula.tv", "www.nebula.tv"],
        "Netflix": ["netflix.com", "www.netflix.com", "nflxvideo.net", "nflximg.net", "nflxext.com"],
        "Paramount+": ["paramountplus.com", "www.paramountplus.com"],
        "Peacock": ["peacocktv.com", "www.peacocktv.com"],
        "Plex": ["plex.tv", "www.plex.tv"],
        "Pluto TV": ["pluto.tv", "www.pluto.tv"],
        "QQ": ["qq.com", "www.qq.com"],
        "Rakuten Viki": ["viki.com", "www.viki.com"],
        "Samsung TV Plus": ["samsungtvplus.com", "www.samsungtvplus.com"],
        "SoundCloud": ["soundcloud.com", "www.soundcloud.com"],
        "Spotify": ["spotify.com", "www.spotify.com", "open.spotify.com", "scdn.co", "spotifycdn.com"],
        "Tidal": ["tidal.com", "www.tidal.com"],
        "Twitch": ["twitch.tv", "www.twitch.tv", "ttvnw.net", "jtvnw.net"],
        "Vimeo": ["vimeo.com", "www.vimeo.com"],
        "Vivo Play": ["vivoplay.com.br", "www.vivoplay.com.br"],
        "Voot": ["voot.com", "www.voot.com"],
        "Weibo": ["weibo.com", "www.weibo.com"],
        "YouTube": ["youtube.com", "www.youtube.com", "m.youtube.com", "youtu.be", "ytimg.com", "googlevideo.com", "youtubei.googleapis.com", "youtube.googleapis.com", "youtube-nocookie.com"],
        "YY": ["yy.com", "www.yy.com"],
    },
    "Other": {
        "Pornhub": ["pornhub.com", "www.pornhub.com", "phncdn.com"],
    },
}

SERVICE_DOMAINS = {
    name: domains
    for services in SERVICE_CATEGORIES.values()
    for name, domains in services.items()
}
